const vondutch = [
  {
    id: '0',
    name: 'Von dutch pink',
    category: 'Shirts',
    front :"/img/caps/vondutch/von2.png",
    back:"/img/caps/vondutch/von2.png",
    side:"/img/caps/vondutch/von2.png",
    price: 30000,
    rating: 4.5,
    size: 10,
    description: 'high quality product',
  },
  {
    id: '1',
    name: 'Von dutch blue',
    category: 'Shirts',
    image: '/img/caps/vondutch/von2.png',
    price: 15000,
    brand: 'Adidas',
    rating: 4.0,
    size: 10,
    description: 'high quality product',
  },
  {
    id: '2',
    name: 'Von dutch black',
    category: 'Shirts',
    image: '/img/caps/vondutch/von3.png',
    price: 15000,
    brand: 'Lacoste',
    rating: 4.8,
    size: 17,
    description: 'high quality product',
  },
  {
    id: '3',
    name: 'Von dutch camoeo',
    category: 'Pants',
    image: '/img/caps/vondutch/von4.png',
    price: 78,
    brand: 'Nike',
    rating: 4.5,
    size: 14,
    description: 'high quality product',
  },
  {
    id: '4',
    name: 'Von dutch skyblue',
    category: 'Pants',
    image: '/img/caps/vondutch/von5.png',
    price: 65,
    brand: 'Puma',
    rating: 4.5,
    size: 10,
    description: 'high quality product',
  },
  {
    id: '5',
    name: 'Von dutch black',
    category: 'Pants',
    image: '/img/caps/vondutch/von6.png',
    price: 139,
    brand: 'Adidas',
    rating: 4.5,
    size: 15,
    description: 'high quality product',
  },
  {
    id: '6',
    name: 'Von dutch blue',
    category: 'Pants',
    image: '/img/caps/vondutch/von7.png',
    price: 139,
    brand: 'Adidas',
    rating: 4.5,
    size: 15,
    description: 'high quality product',
  },
]


export default vondutch;