const products = [
  {
    id: '0',
    name: 'Nike Slim Shirt',
    category: 'Shirts',
    image: '/img/shoes/men/luis/1.jpg',
    price: 120,
    brand: 'Nike',
    rating: 4.5,
    size: 10,
    description: 'high quality product',
  },
  {
    id: '1',
    name: 'Adidas Fit Shirt',
    category: 'Shirts',
    image: '/img/shoes/men/luis/2.jpg',
    price: 100,
    brand: 'Adidas',
    rating: 4.0,
    size: 10,
    description: 'high quality product',
  },
  {
    id: '2',
    name: 'Lacoste Free Shirt',
    category: 'Shirts',
    image: '/img/shoes/men/luis/3.jpg',
    price: 220,
    brand: 'Lacoste',
    rating: 4.8,
    size: 17,
    description: 'high quality product',
  },
  {
    id: '3',
    name: 'Nike Slim Pant',
    category: 'Pants',
    image: '/img/shoes/men/luis/4.jpg',
    price: 78,
    brand: 'Nike',
    rating: 4.5,
    size: 14,
    description: 'high quality product',
  },
  {
    id: '4',
    name: 'Puma Slim Pant',
    category: 'Pants',
    image: '/img/shoes/men/luis/5.jpg',
    price: 65,
    brand: 'Puma',
    rating: 4.5,
    size: 10,
    description: 'high quality product',
  },
  {
    id: '5',
    name: 'Adidas Fit Pant',
    category: 'Pants',
    image: '/img/shoes/men/luis/2.jpg',
    price: 139,
    brand: 'Adidas',
    rating: 4.5,
    size: 15,
    description: 'high quality product',
  },
]

export default products;